name: Package
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Package

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check
      with:
        file-name: package.json
        diff-search: true
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: npm ci
    - name: Lint
      if: steps.check.outputs.changed == 'true'
      run: |
        npm run format-check
        npm run lint
    - name: Build
      if: steps.check.outputs.changed == 'true'
      run: npm run build
    - name: Run tests
      if: steps.check.outputs.changed == 'true'
      run: npm run test
    - name: Package Chrome
      if: steps.check.outputs.changed == 'true'
      run: npm run package:chrome
    - name: Package Firefox
      if: steps.check.outputs.changed == 'true'
      run: npm run package:firefox
    - name: Package Opera
      if: steps.check.outputs.changed == 'true'
      run: npm run package:opera
    - name: Upload - Chrome package
      if: steps.check.outputs.changed == 'true'
      uses: actions/upload-artifact@v1
      with:
        name: chrome
        path: package/chrome
    - name: Upload - Firefox package
      if: steps.check.outputs.changed == 'true'
      uses: actions/upload-artifact@v1
      with:
        name: firefox
        path: package/firefox
    - name: Upload - Opera package
      if: steps.check.outputs.changed == 'true'
      uses: actions/upload-artifact@v1
      with:
        name: opera
        path: package/opera
